"""Utilities for cleaning Markdown + LaTeX generated by LLMs."""
from __future__ import annotations

import re

_CHINESE_RE = re.compile(r'[\u4e00-\u9fff\u3000-\u303f\uff00-\uffef]')


def sanitize_latex(text: str) -> str:
    """Normalize common LaTeX delimiter issues before frontend rendering."""
    text = _strip_latex_spacing_options(text)
    text = _convert_tex_delimiters(text)
    return _balance_math_delimiters(text)


def _strip_latex_spacing_options(text: str) -> str:
    # Convert line breaks like \\[4pt] to a plain LaTeX line break.
    return re.sub(r'\\\\\s*\[(?:\d+(?:\.\d+)?)(?:pt|em|ex|mm|cm|in)\]', r'\\\\', text)


def _convert_tex_delimiters(text: str) -> str:
    text = re.sub(r'(?<!\\)\\\((.+?)(?<!\\)\\\)', r'$\1$', text, flags=re.DOTALL)
    text = re.sub(r'(?<!\\)\\\[(.+?)(?<!\\)\\\]', r'$$\1$$', text, flags=re.DOTALL)
    return text


def _is_escaped(text: str, index: int) -> bool:
    slash_count = 0
    i = index - 1
    while i >= 0 and text[i] == '\\':
        slash_count += 1
        i -= 1
    return slash_count % 2 == 1


def _find_chinese_outside_braces(text: str) -> int | None:
    depth = 0
    escaped = False
    for idx, ch in enumerate(text):
        if escaped:
            escaped = False
            continue
        if ch == '\\':
            escaped = True
            continue
        if ch == '{':
            depth += 1
        elif ch == '}':
            depth = max(0, depth - 1)
        elif depth == 0 and _CHINESE_RE.match(ch):
            return idx
    return None


def _first_non_whitespace(text: str) -> int | None:
    for idx, ch in enumerate(text):
        if not ch.isspace():
            return idx
    return None


def _next_unescaped(text: str, token: str) -> int:
    start = 0
    while True:
        idx = text.find(token, start)
        if idx == -1:
            return -1
        if not _is_escaped(text, idx):
            return idx
        start = idx + len(token)


def _balance_math_delimiters(text: str) -> str:
    result: list[str] = []
    i = 0
    n = len(text)

    while i < n:
        if text.startswith(r'\$', i):
            result.append(r'\$')
            i += 2
            continue

        if text.startswith('$$', i) and not _is_escaped(text, i):
            rest = text[i + 2:]
            first = _first_non_whitespace(rest)
            if first is not None and _CHINESE_RE.match(rest[first]):
                close = _next_unescaped(rest, '$$')
                if close >= 0:
                    result.append(rest[:close])
                    i += 2 + close + 2
                else:
                    result.append(rest)
                    i = n
                continue

            close = _next_unescaped(rest, '$$')
            chinese = _find_chinese_outside_braces(rest)
            if close >= 0 and (chinese is None or close < chinese):
                result.extend(['$$', rest[:close], '$$'])
                i += 2 + close + 2
            elif chinese is not None:
                math_content = rest[:chinese]
                stripped = math_content.rstrip()
                result.extend(['$$', stripped, '$$', math_content[len(stripped):]])
                i += 2 + chinese
            else:
                result.extend(['$$', rest, '$$'])
                i = n
            continue

        if text[i] == '$' and not _is_escaped(text, i):
            rest = text[i + 1:]
            first = _first_non_whitespace(rest)
            if first is not None and _CHINESE_RE.match(rest[first]):
                close = _next_unescaped(rest, '$')
                if close >= 0:
                    result.append(rest[:close])
                    i += 1 + close + 1
                else:
                    result.append(rest)
                    i = n
                continue

            close = _next_unescaped(rest, '$')
            chinese = _find_chinese_outside_braces(rest)
            if close >= 0 and (chinese is None or close < chinese):
                result.extend(['$', rest[:close], '$'])
                i += 1 + close + 1
            elif chinese is not None:
                math_content = rest[:chinese]
                stripped = math_content.rstrip()
                result.extend(['$', stripped, '$', math_content[len(stripped):]])
                i += 1 + chinese
            else:
                result.extend(['$', rest, '$'])
                i = n
            continue

        result.append(text[i])
        i += 1

    return ''.join(result)
